version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: to-do-app
    depends_on:
      - db
    environment:
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  db_data:
